### ISSUE TITLE
Not an isse, only an idea/request

### ISSUE THREAD

**Issue by ermurenz** [mo-azfar/OTRS-Ticket-Auto-Allocation#1]
Hi,
 it seems to me a beautiful project that I would like to implement in our infrastructure.
We were trying to replicate this kind of thing in another way (through bash scripts, selects direct to the db and znuny webservice), but we're struggling.
Having such a thing as OTRS-Ticket-Auto-Allocation, it would be a game-changer.
We were wondering if it was possible to add a filter in order to assign tickets only to those who are online at the time the job starts.
Would be great.
I am not a perl expert otherwise I would have tried to contribute.
Can you possibly give me some references or advice to integrate the necessary lines?
if you can't, it's okay.
Thank you in advance.
Great project, congratulations.

Emanuele

**Comment by mo-azfar** [comment]
You may refer https://doc.znuny.org/doc/api/otrs/6.0/Perl/Kernel/System/AuthSession.pm.html

actually, it was in my todo list to make it based on online agent, i see what i can do at the end of the week / month.

**Comment by mo-azfar** [comment]
applied

**Comment by ermurenz** [comment]
oh my god i really thank you, you saved me.
