### ISSUE TITLE
Global symbol "$SessionObject" requires explicit package name

### ISSUE THREAD

**Issue by ermurenz** [mo-azfar/OTRS-Ticket-Auto-Allocation#2]
Hi @mo-azfar ,
Thank you for the recent update.We love it.
I was testing on our systems  (we have two servers with Znuny LTS 6.0.39) the new changes and we got this error on both.
Exactly the same output.

"Global symbol "$SessionObject" requires explicit package name (did you forget to declare "my $SessionObject"?) at /opt/otrs/Custom/Kernel/System/GenericAgent/TicketAutoAllocation.pm line 76."

Of course no auto-assigment.
Can be something relate to our servers (versions or misconfiguations) or it's something else?

thank you  in advanced, again.

**Comment by mo-azfar** [comment]
fixed

**Comment by ermurenz** [comment]
it works!!! 
I can't explain the gratitude.
